---
title: "pitch_roll"
author: "Lilah McCormick"
date: '2022-07-07'
output: 
  html_document:
    toc: yes
    toc_float: yes 
    theme: default 
    highlights: monotone
---
### Load libraries: 
```{r load libraries, echo = FALSE}
library(tidyverse)
library(lubridate)
```

### Data manipulation: 
#### Overarching Task: Write two R functions that take acceleration as the input and return pitch and roll

```{r read_acc_func}
# can make this a more streamlined function 

# read_acc creates a dataframe with columns acceleration (in g) and DateTime to minimize repetitive coding. 

#Parameters: 
# x_path, y_path, z_path = name of text file for x,y,z axis acceleration. eg: "name_of_file.txt"
# nrow = number of rows to read. eg: 10000. Default = Inf

read_acc <- function(x_path, y_path, z_path, nrow = Inf) {
  accx <- read_tsv(x_path, 
                   col_names = c("acc_x", "drop", "DateTime"), 
                   n_max = nrow) %>% 
    mutate(DateTime = mdy_hms(DateTime), 
           acc_x = acc_x / 1000) %>% # makes units g
    select(-drop) #removes "%" column 
  
  accy <- read_tsv(y_path, 
                   col_names = c("acc_y", "drop", "DateTime"), 
                   n_max = nrow) %>% 
    mutate(DateTime = mdy_hms(DateTime), 
           acc_y = acc_y / 1000) %>% # makes units g
    select(-drop) #removes drop column 
  
  accz <- read_tsv(z_path, 
                   col_names = c("acc_z", "drop", "DateTime"), 
                   n_max = nrow) %>% 
    mutate(DateTime = mdy_hms(DateTime), 
           acc_z = acc_z / 1000) %>% # makes units g
    select(-drop) #removes "%" column 
  
  # Assert datetimes are all the same
  stopifnot(all(accx$DateTime == accy$DateTime),
            all(accx$DateTime == accz$DateTime))
  
  accx %>% 
    mutate(acc_y = accy$acc_y,
           acc_z = accz$acc_z) %>%  #combine acc columns into one df with DateTime
    relocate(DateTime) #move DateTime col to front 
}

# #Read accx function - can't make this work yet. 
# read_accx <- function(x_path, nrow){
#   accx <- read_tsv(x_path, 
#                    col_names = c("acc_x", "drop", "DateTime"), 
#                    n_max = nrow) %>% 
#     mutate(DateTime = mdy_hms(DateTime), 
#            acc_x = acc_x / 1000) %>% # makes units g
#     select(-drop) #removes "%" column 
#   accx
# }
# 
# accx <- read_accx(x_path = "HDI0_Asgeir.txt", nrow = 10)
```
 
```{r read_into_wide }
acc_wide <- read_acc("HDI0_Asgeir.txt", 
                     "HDJ0_Asgeir.txt", 
                     "HDK0_Asgeir.txt", 
                     nrow = 4e6)
```

```{r pivot_longer=}
acc_long <- acc_wide %>% 
  pivot_longer(!DateTime, 
               names_to = "axis", 
               values_to = "acc")
```

```{r anorm}
#calculate anorm
anorm <- function(xyz) {
  sqrt(rowSums(xyz * xyz))
}
#plot anorm vs. DateTime
start_time <- ymd_hms('2018-08-24 08:26:01')
end_time <- ymd_hms('2018-08-24 08:57:00')

acc_wide <- acc_wide %>% 
  mutate(anorm = anorm(cbind(acc_x, acc_y, acc_z)))  # a bit confused on what this does still 
  
#plot anorm vs. DateTime
filter(acc_wide, DateTime >= start_time, DateTime <= end_time) %>% 
  ggplot(aes(DateTime, anorm)) +
  geom_line() +
  theme_bw()

##Why can I not get this plot to work as a pipe connected to the anorm mutate function


```

```{r pitch}
# p = -asin(acc_x)(anorm)
# read_accx (this should be part of a function in the end)
accx <- read_tsv("HDI0_Asgeir.txt", 
                 col_names = c("acc_x", "drop", "DateTime"), 
                 n_max = 4e6) %>% 
  mutate(DateTime = mdy_hms(DateTime), 
         acc_x = acc_x / 1000) %>% # makes units g
  select(-drop) #removes "%" column 

#add pitch column 
acc_wide <- acc_wide %>% 
  mutate(pitch = -asin(acc_x)) 

#plot pitch 
filter(acc_wide, DateTime >= start_time, DateTime <= end_time) %>% 
  ggplot(aes(DateTime, pitch)) +
  geom_line() +
  theme_bw()

#appears as if they define positive pitch as animal tilted downward (head-first). 
```

```{r roll }
accy  <- read_tsv("HDJ0_Asgeir.txt", 
                 col_names = c("acc_y", "drop", "DateTime"), 
                 n_max = 4e6) %>% 
  mutate(DateTime = mdy_hms(DateTime), 
         acc_y = acc_y / 1000) %>% # makes units g
  select(-drop) #removes "%" column 

accz  <- read_tsv("HDK0_Asgeir.txt", 
                 col_names = c("acc_z", "drop", "DateTime"), 
                 n_max = 4e6) %>% 
  mutate(DateTime = mdy_hms(DateTime), 
         acc_z = acc_z / 1000) %>% # makes units g
  select(-drop) #removes "%" column 

# add roll column 
acc_wide <- acc_wide %>% 
  mutate(roll = atan(acc_y/acc_z))  

#plot roll
filter(acc_wide, DateTime >= start_time, DateTime <= end_time) %>% 
  ggplot(aes(DateTime, roll)) +
  geom_line() +
  theme_bw()
  
```



____________________________________________________________________________________




##### Step 2: Connect I,J,K to Surge, Sway, Heave
```{r plot_acc_func}
# plot_dive_func plots an acceleration vs. time graph given a set of parameters to minimize repetition of code when plotting acceleration  profiles at multiple timescales.

# Parameters: 
# dataframe - must be a dataframe. 
# start_time/end_time - must be character strings in 'YYYY-MM-DD hh:mm:ss' format.
# title - must be a character string in "Graph Title" format. 

plot_acc <- function(dataframe, start_time, end_time, title) {
  one_dive <- filter(dataframe, DateTime >= start_time, DateTime <= end_time)
  ggplot(one_dive, aes(x = DateTime, y = Acceleration)) +
    geom_line() +
    labs(title = title,
         x = "Time",
         y = "acceleration") + #changes labels on axes and title 
    theme_bw()  #white background
}
```

```{r plot_dive_profile_func}
# plot_dive_func plots a dive profile given a set of parameters to minimize repetition of code when plotting dive profiles at multiple timescales.

# Parameters: 
# dataframe - must be a dataframe. 
# start_time/end_time - must be character strings in 'YYYY-MM-DD hh:mm:ss' format.
# title - must be a character string in "Graph Title" format. 

plot_dive <- function(dataframe, start_time, end_time, title) {
  one_dive <- filter(dataframe, DateTime >= start_time, DateTime <= end_time)
  dive_plot <- ggplot(one_dive, aes(x = DateTime, y = Depth)) +
    geom_line() +
    scale_y_reverse() + #makes depth right orientation 
    labs(title = title,
        x = "Time",
        y = "Depth (m)") + #changes labels on axes and title 
    theme_bw()  #white background
  dive_plot
}
```


```{r plot accleration next to dive profile}
#plot acceleration together 
start_time <- ymd_hms('2018-08-24 08:26:01')
end_time <- ymd_hms('2018-08-24 08:57:00')

one_dive <- filter(acc_long, DateTime >= start_time, DateTime <= end_time)
ggplot(one_dive, aes(x = DateTime, y = acc, color = axis)) +
  geom_line() +
  labs(x = "Time",
       y = "acceleration") + #changes labels on axes and title 
  theme_bw()  #white background

#Plot acceleration separately 
plot_acc(acc_x, start_time, end_time, "accleration i")
plot_acc(acc_y, start_time, end_time, "accleration j")
plot_acc(acc_z, start_time, end_time, "accleration k")

#Plot depth 
depth_data <- read_tsv("Depth_Asgeir.txt") %>% #read file 
  mutate(DateTime = mdy_hms(`Date time`), .keep = "unused") #fix datetime
plot_dive(depth_data, start_dive, end_dive, "Depth Profile")

```


