---
title: "bcg_plots"
author: "Lilah McCormick"
date: "2022-08-10"
output: html_document
---

```{r}
source("src/data.R")
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(stringr)
library(knitr)
```

```{r}
balder_bcg <- readRDS(find_BCG("balder")) %>% 
  filter(rid == "251") %>% 
  slice(100:2500) #cuts down data to 24 seconds 

```

```{r filtered_acc}
#FIXME need to fix x axis time ticks 
filt_acc <- balder_bcg %>% 
  select("DateTime", "acc_x_filt", "acc_y_filt", "acc_z_filt") %>% 
  pivot_longer(
    cols = acc_x_filt:acc_z_filt, 
    names_to = "axis",
    values_to = "acc_filt"
  )


filt_acc_plot <- ggplot(filt_acc, aes(x = DateTime, y = acc_filt, color = axis)) +
  geom_line() +
  facet_wrap(vars(axis), 
             nrow = 3) +
  theme(legend.position = "none",
        strip.background = element_blank(),
        strip.text = element_blank(),
        line = element_blank(), 
        rect = element_blank(), 
        axis.text.y = element_blank(),
        axis.title.y = element_text(size = 20), 
        axis.title.x = element_text(size = 20)) + 
  labs(x = "time",
       y = str_wrap("filtered acceleration", 10)
  )


filt_acc_plot
```

```{r differenced_acc}
diff_acc <- balder_bcg %>% 
  mutate(jerk_x = jerk[,1], jerk_y = jerk[,2], jerk_z = jerk[,3]) %>% 
  select(DateTime, jerk_x, jerk_y, jerk_z) %>% 
  pivot_longer(
    cols = jerk_x:jerk_z, 
    names_to = "axis",
    values_to = "acc_diff"
  )

diff_acc_plot <- ggplot(diff_acc, aes(x = DateTime, y = acc_diff, color = axis)) +
  geom_line() +
  facet_wrap(vars(axis), 
             nrow = 3) +
  theme(legend.position = "none",
        strip.background = element_blank(),
        strip.text = element_blank(),
        line = element_blank(), 
        rect = element_blank(),
        axis.title.y = element_text(size = 20),
        axis.text.y = element_blank(), 
        axis.title.x = element_text(size = 20)) + 
  labs(x = "time",
       y = str_wrap("differenced acceleration", 10)
  )

diff_acc_plot
```

```{r se}
se <- balder_bcg %>% 
  select(DateTime, jerk_se)

se_plot <- ggplot(se, aes(x = DateTime, y = jerk_se)) +
  geom_line() +
  theme(strip.background = element_blank(),
        strip.text = element_blank(),
        line = element_blank(), 
        rect = element_blank(), 
        axis.text.y = element_blank(),
        axis.title.y = element_text(size = 20), 
        axis.title.x = element_text(size = 20)) + 
  labs(x = "time",
       y = str_wrap("shannon entropy", 10)
  )

se_plot
```

```{r smooth}
smooth <- balder_bcg %>% 
  select(DateTime, jerk_smooth)

smooth_plot <- ggplot(smooth, aes(x = DateTime, y = jerk_smooth)) +
  geom_line() +
  theme(strip.background = element_blank(),
        strip.text = element_blank(),
        line = element_blank(), 
        rect = element_blank(), 
        axis.text.y = element_blank(),
        axis.title.y = element_text(size = 20), 
        axis.title.x = element_text(size = 20)) + 
  labs(x = "time",
       y = str_wrap("smoothed signal", 10)
  )

smooth_plot

ggsave("figures/balder_bcg_smooth.jpg", smooth_plot, device = "jpeg", width = 15, height = 3)
#FIXME this looks seriously wrong
```

```{r arrange}
bcg_plots <- list(filt_acc_plot, diff_acc_plot, se_plot, smooth_plot) %>% map(~.x + labs(x=NULL))

bcg_plot_comb <- grid.arrange(grobs = bcg_plots, 
             nrow = 4, 
             bottom = textGrob("time(s)", gp=gpar(fontsize=20)))

ggsave("figures/balder_bcg_plots_poster.jpg", bcg_plot_comb, device="jpeg", width = 10, height = 7)
```

```{r s2n table}
max_s2ns <- as_tibble(readRDS("data/derived_data/balder_s2ns_bottom_0515.rds")) %>% 
  slice_max(s2n, n = 10) %>% 
  relocate(dive_phase) %>% 
  rename("window size" = win_size, "upper frequency cutoff" = upper, "dive phase" = dive_phase, "signal/noise" = s2n)



library(kableExtra)
kable(max_s2ns, table.attr = "style='width:150%;'") %>%
  kable_styling("striped", full_width = T)


```

