---
title: "Depth Profiles"
author: "Lilah McCormick"
date: '2022-06-30'
output: 
  html_document:
    toc: yes
    toc_float: yes 
    theme: default 
    highlights: monotone
---

#### Before Starting: Load libraries
```{r = load_packages, message = FALSE, results = FALSE}
library(lubridate)
library(tidyverse)
library(plotly)
library(DT)
library(glue)
source("src/util.R")
source("src/data.R")
```

#### Read filed into a dataframe, and make DateTimes compatible with POSIXct
```{r = fix_datetimes, message = FALSE, results = FALSE}
depth_asgeir <- read_depth(find_depth("asgeir"))
depth_balder <- read_depth(find_depth("balder"))
```

#### Dive Profile Plots:  
```{r = plot_asgeir_depth, echo = FALSE, messages = FALSE}
# plot whole deployment 
start_dep_asgeir <- depth_asgeir$DateTime[1]
end_dep_asgeir <- depth_asgeir$DateTime[nrow(depth_asgeir)]
plot_dive(depth_asgeir, start_dep_asgeir, end_dep_asgeir, "Asgeir Dive Profile 2018 Deployment")
#plot day
start_day <- ymd_hms('2018-08-24 00:00:00')
end_day <- start_day + days(1)
plot_dive(depth_asgeir, start_day, end_day, "Asgeir Dive Profile August 24, 2018")
#plot one dive 
start_dive <- ymd_hms('2018-08-24 08:26:01')
end_dive <- ymd_hms('2018-08-24 08:49:04')
plot_dive(depth_asgeir, start_dive, end_dive, "Asgeir Dive Profile Single Dive August 24, 2018", TRUE)
```

```{r plot_balder_depth, echo = FALSE, messages = FALSE}
start_dep_balder <- 	depth_balder$DateTime[1]
end_dep_balder <- depth_balder$DateTime[nrow(depth_balder)]
plot_dive(depth_balder, start_time, end_time, "Balder Dive Profile 2018 Deployment", TRUE)
```


```{r plot_dive_phases}
start_time <- ymd_hms('2016-08-24 20:43:13')
end_time <- ymd_hms('2016-08-24 21:02:20')

sur_start <- ymd_hms('2016-08-24 20:43:13')
sur_end <- ymd_hms('2016-08-24 20:45:23')

des_start <- ymd_hms('2016-08-24 20:45:23')
des_end <- ymd_hms('2016-08-24 20:49:16')

bot_start <- ymd_hms('2016-08-24 20:49:16')
bot_end <- ymd_hms('2016-08-24 20:51:23')

asc_start <- ymd_hms('2016-08-24 20:51:23')
asc_end <- ymd_hms('2016-08-24 20:55:47')

sur_start_1 <- ymd_hms('2016-08-24 20:55:47')
sur_end_1 <- ymd_hms('2016-08-24 20:57:58')

sub_start <- ymd_hms('2016-08-24 20:57:58')
sub_end <- ymd_hms('2016-08-24 21:01:09')

sur_start_2 <- ymd_hms('2016-08-24 21:01:09')
sur_end_2 <- ymd_hms('2016-08-24 21:02:20')

one_dive <- filter(depth_balder, DateTime >= start_time, DateTime <= end_time) %>% 
  mutate(phase = case_when( #assign a dive phase to each time point 
    DateTime > des_start & DateTime <= des_end ~ "descent",
    DateTime > bot_start & DateTime <= bot_end ~ "bottom", 
    DateTime > asc_start & DateTime <= asc_end ~ "ascent",
    DateTime > sub_start & DateTime <= sub_end ~ "subsurface",
    (DateTime >= sur_start & DateTime <= sur_end) |
      (DateTime > sur_start_1 & DateTime <= sur_end_1) |
      (DateTime > sur_start_2 & DateTime <= sur_end_2)  ~ "surface"
  ), 
  phase = factor(phase, levels = c("surface", "descent", "bottom", "ascent", "subsurface"))) #reorder the dive phases in the plot legend 

dive_plot <- ggplot(one_dive, aes(x = DateTime, y = Depth, color = phase, group = 1)) +
  geom_line(size = 1.2) +
  scale_y_reverse() + #makes depth right orientation 
  labs(x = "Time",
       y = "Depth (m)") + #changes labels on axes and title 
  theme(line = element_blank(), 
        rect = element_blank(), 
        text = element_text(size = 16),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        legend.title = element_blank()
  ) + 
  scale_color_manual(values = c("#A6D854", "#FC8D62", "#77CCFF", "#E78AC3", "#8DA0CB")) #choose color scheme
dive_plot

#ggsave("figures/balder_dive_phases.jpg", dive_plot, device="jpeg", width = 10, height = 7)
```

