---
title: "pitch_roll"
author: "Lilah McCormick"
date: '2022-07-07'
output: 
  html_document:
    toc: yes
    toc_float: yes 
    theme: default 
    highlights: monotone
---
load libraries: 
```{r load libraries, echo = FALSE, message = FALSE}
library(tidyverse)
library(lubridate)
source("src/util.R")
source("src/data.R")
```

```{r read,  echo = FALSE, message = FALSE}
ten_hz_asgeir <- readRDS(find_10hz("asgeir"))
```

```{r pra_long, echo = FALSE, message = FALSE}
pra_long <- ten_hz_asgeir %>% 
  subset(select = c(DateTime, pitch, roll, anorm)) %>% 
  pivot_longer(!DateTime, 
               names_to = "metric", 
               values_to = "value")
```

```{r ml_highlighted}
#make a plot with time on x axis, and pitch, roll and anorm on y axis using facetwrap
des_start <- ymd_hms('2018-08-27 15:42:20')
ml_start <- ymd_hms('2018-08-27 15:42:30')
ml_end <- ymd_hms('2018-08-27 15:42:45')
des_end <- ymd_hms('2018-08-27 15:42:55')

pra_ml <- pra_long %>% 
  filter(DateTime >= des_start, DateTime <= des_end) %>% 
  mutate(ml = case_when( #assign a dive phase to each time point 
    DateTime <= ml_start | DateTime > ml_end ~ "movement",
    DateTime > ml_start & DateTime <= ml_end ~ "static"))

pra_ml$metric[pra_ml$metric == "anorm"] <- "||A||"

pra_plot <- ggplot(pra_ml, aes(x = DateTime, y = value, color = ml, group = 1)) +
  geom_line() +
  facet_wrap(vars(metric), nrow = 3, scales = "free", strip.position = "left") +
  theme(line = element_blank(),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 16),
        legend.text = element_text(size = 16),
        strip.text.y = element_text(size = 16),
        panel.background = element_rect(fill = "#F5F5F5", colour = "#F5F5F5")) +
  labs(x = "time(s)",
       y = NULL,
       color = NULL) +
  scale_color_manual(values = c("808080", "#E78AC3"))

pra_plot

ggsave("figures/static_period.jpg", pra_plot, device="jpeg", width = 10, height = 7)
```


```{r bottom_plot}
#plot pra for bottom phase of a dive for a narwhal 
bot_start <- ymd_hms('2018-08-25 22:07:43') 
bot_end <- ymd_hms('2018-08-25 22:10:54')

pra_bottom <- pra_long %>% 
  filter(DateTime >= bot_start, DateTime <= bot_end)

pra_bottom$metric[pra_bottom$metric == "anorm"] <- "||A||"

pra_bot_plot <- ggplot(pra_bottom, aes(x = DateTime, y = value)) +
  geom_line() +
  facet_wrap(vars(metric), nrow = 3, scales = "free", strip.position = "left") +
  theme(line = element_blank(), 
        axis.text.x = element_text(size = 12),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 16),
        legend.text = element_text(size = 16),
        strip.text.y = element_text(size = 16)) +
  labs(x = "time(h:m)", 
       y = NULL) 

pra_bot_plot

ggsave("figures/asgeir_pra_bottom.jpg", dev = "jpeg", width = 10, height = 7)

```


