---
title: "10hz_pitch_roll"
author: "Lilah McCormick"
date: '2022-07-18'
output: 
  html_document:
    toc: yes
    toc_float: yes 
    theme: default 
    highlights: monotone
---
load libraries: 
```{r load, echo = FALSE, message = FALSE}
library(tidyverse)
library(lubridate)
source("src/util.R")
source("src/data.R")
```

```{r read,  echo = FALSE, message = FALSE}
#calc_pra calculates pitch, roll, and anorm columns and adds them onto a tri-axial acc. df with dt. 
#parameters: 
#narwhal_id - the name of the narwhal in quotes. eg: "asgeir"
#nrow - number of rows to read from the tsv file. Default is Inf (infinite)

calc_pra <- function(narwhal_id, nrow = Inf) {
  read_acc(narwhal_id, nrow) %>% 
  mutate(anorm = anorm(cbind(acc_x, acc_y, acc_z)),
         pitch = pitch(acc_x, anorm),
         roll = roll(acc_y, acc_z)) 
}

acc_wide_asgeir <- calc_pra("asgeir", Inf)
depth_asgeir <- read_depth(find_depth("asgeir"))   

acc_wide_balder <- calc_pra("balder", Inf)
depth_balder <- read_depth(find_depth("balder"))
```

```{r combine, echo = FALSE, message = FALSE}

#comb_acc_depth takes in a acc_wide 100hz and depth 1hz  df and combines them to create a 10hz df. 
#Parameters: 
#acc_wide - the acceleration df at 100hz
#depth - the depth df at 1hz. 

comb_acc_depth <- function(acc_wide, depth) {
  acc_wide %>% 
    slice(seq(1, nrow(acc_wide), 10)) %>% #extracts every 10th row
    mutate(depth = approx(depth$DateTime, depth$Depth, xout = DateTime)$y) %>% 
    left_join(select(depth, DateTime), by = "DateTime") %>% 
    drop_na(depth)
}

ten_hz_asgeir <- comb_acc_depth(acc_wide_asgeir, depth_asgeir)
ten_hz_balder <- comb_acc_depth(acc_wide_balder, depth_balder)
                                
```

```{r save, echo = FALSE, message = FALSE}
saveRDS(ten_hz_asgeir, "data/derived_data/biologging/Asgeir_10hz.rds")
saveRDS(ten_hz_balder, "data/derived_data/biologging/Balder_10hz.rds")
```


