---
title: "pitch_roll"
author: "Lilah McCormick"
date: '2022-07-07'
output: 
  html_document:
    toc: yes
    toc_float: yes 
    theme: default 
    highlights: monotone
---
load libraries: 
```{r load libraries, echo = FALSE, message = FALSE}
library(tidyverse)
library(lubridate)
source("src/util.R")
source("src/data.R")
```

```{r read_into_wide,  echo = FALSE, message = FALSE}
acc_wide_asgeir <- read_acc("asgeir",  nrow = Inf) %>% 
  mutate(anorm = anorm(cbind(acc_x, acc_y, acc_z)),
         pitch = pitch(acc_x, anorm),
         roll = roll(acc_y, acc_z)) 
```

```{r pivot_longer, echo = FALSE, message = FALSE}
acc_long <- acc_wide_asgeir %>% 
  subset(select = c(DateTime, acc_x, acc_y, acc_z)) %>% 
  pivot_longer(!DateTime, 
               names_to = "axis", 
               values_to = "acc")

pra_long <- acc_wide_asgeir %>% 
  subset(select = c(DateTime, pitch, roll, anorm)) %>% 
  pivot_longer(!DateTime, 
               names_to = "metric", 
               values_to = "value")
```

plot figures: 
```{r plot figures, echo = FALSE, message = FALSE}
#define start and end times: 
start_time <- ymd_hms('2018-08-24 08:26:01')
end_time <- ymd_hms('2018-08-24 08:57:00')

#plot depth
depth_data <- read_depth(find_depth("asgeir"))
plot_dive(depth_data, start_time, end_time)

#plot anorm
plot_calculated(acc_wide_asgeir, start_time, end_time, anorm)

#plot pitch
plot_calculated(acc_wide_asgeir, start_time, end_time, pitch)
#appears as if they define positive pitch as animal tilted downward (head-first)

#plot roll
plot_calculated(acc_wide_asgeir, start_time, end_time, roll)

#plot acceleration 
plot_acc(acc_long, start_time, end_time)
```


```{r plot_tsviewer window}
#make a plot with time on x axis, and pitch, roll and anorm on y axis using facetwrap
start_plot <- ymd_hms('2018-08-27 15:42:20')
start_ml <- ymd_hms('2018-08-27 15:42:30')
end_ml <- ymd_hms('2018-08-27 15:42:45')
end_plot <- ymd_hms('2018-08-27 15:42:55')

pra_ml <- pra_long %>% 
  filter(DateTime >= start_plot, DateTime <= end_plot) %>% 
  mutate(ml = case_when( #assign a dive phase to each time point 
    DateTime <= start_ml | DateTime > end_ml ~ "movement",
    DateTime > start_ml & DateTime <= end_ml ~ "static"))


pra_plot <- ggplot(pra_ml, aes(x = DateTime, y = value, color = ml, group = 1)) +
  geom_line() +
  facet_wrap(vars(metric), nrow = 3, scales = "free", strip.position = "left") +
  theme(line = element_blank(),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 16),
        legend.text = element_text(size = 16),
        strip.text.y = element_text(size = 16),
        panel.background = element_rect(fill = "#F5F5F5", colour = "#F5F5F5")) +
  labs(x = "time(s)",
       y = NULL,
       color = NULL) +
  scale_color_manual(values = c("808080", "#E78AC3"))
                     
# Poster Figure Modifications: 
# pra_ml$metric[pra_ml$metric == "anorm"] <- "acceleration"
# 
# pra_plot <- ggplot(pra_ml, aes(x = DateTime, y = value, color = ml, group = 1)) +
#   geom_line() +
#   facet_wrap(vars(metric), nrow = 3, scales = "free", strip.position = "left") +
#   theme(line = element_blank(), 
#         axis.text.x = element_text(size = 12),
#         axis.text.y = element_blank(),
#         axis.title.x = element_text(size = 28),
#         legend.position = "none",
#         strip.text.y = element_text(size = 28),
#         panel.background = element_rect(fill = "#F5F5F5", colour = "#F5F5F5")) +
#   labs(x = "time(s)", 
#        y = NULL, 
#        color = NULL) +
#   scale_color_manual(values = c("808080", "#E78AC3"))

pra_plot

ggsave("figures/static_period_poster.jpg", pra_plot, device="jpeg", width = 10, height = 7)
```
                     
```{r bottom_plot_nar}
bot_start <- ymd_hms('2018-08-25 22:07:43') 
bot_end <- ymd_hms('2018-08-25 22:10:54')

pra_bottom <- pra_long %>% 
  filter(DateTime >= bot_start, DateTime <= bot_end)

pra_bot_plot <- ggplot(pra_bottom, aes(x = DateTime, y = value)) +
  geom_line() +
  facet_wrap(vars(metric), nrow = 3, scales = "free", strip.position = "left") +
  theme(line = element_blank(), 
        axis.text.x = element_text(size = 12),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 16),
        legend.text = element_text(size = 16),
        strip.text.y = element_text(size = 16)) +
  labs(x = "time(h:m)", 
       y = NULL) 
  
pra_bot_plot

ggsave("figures/asgeir_pra_bottom.jpg", dev = "jpeg", width = 10, height = 7)

```

                     
                     